import { recallMemories, saveMemory, formatMemories, memoryEnabled } from "./memory.js";
import { councilRoute } from "./council.js";
import { runControlledTask } from "./master-control.js";

const SYSTEM_PROMPT = `You are K.AI.S (Knowledge & Artificial Intelligence System), the Master AI layer of MA-AIPS. Help students understand studies, plan learning, identify weaknesses, improve performance, and stay motivated. Give clear, practical, accurate answers. Never help students cheat or impersonate another. Use supplied long-term memories when relevant. If an older event is not in memory, say so instead of inventing it. Preserve dates and sequence accurately. You are operating as part of a specialized MA-AI.PS department. Stay within the assigned department mission and escalate when a task requires CEO approval, sensitive actions, or capabilities not actually connected. Master AI authority is above all departments; departments execute assigned work and cannot override Master AI or CEO policy.`;
const DEFAULT_TIMEOUT_MS = Number(process.env.MASTER_AI_TASK_TIMEOUT_MS || 30000);

function normalizeMessages(history){if(!Array.isArray(history))return [];return history.slice(-10).map(m=>({role:m.role==="assistant"?"assistant":"user",content:String(m.content||"").slice(0,2000)}));}
function configuredProviders(){const preferred=String(process.env.AI_PROVIDER||"").trim().toLowerCase();const available={groq:Boolean(process.env.GROQ_API_KEY),openai:Boolean(process.env.OPENAI_API_KEY),gemini:Boolean(process.env.GEMINI_API_KEY)};const order=preferred==="groq"?["groq","openai","gemini"]:preferred==="openai"?["openai","groq","gemini"]:preferred==="gemini"?["gemini","groq","openai"]:["groq","openai","gemini"];return order.filter(n=>available[n]);}
function systemPrompt(studentId,language,councilRole,memories){const memoryText=memories?.length?`\n\nLONG-TERM MEMORY RECORDS:\n${formatMemories(memories)}`:"\n\nLONG-TERM MEMORY RECORDS: none matched this request.";return `${SYSTEM_PROMPT}\nContext identifier: ${studentId||"unknown"}${language?`\nRespond in ${language}.`:""}${councilRole?`\nAssigned MA-AI.PS department: ${councilRole}.`:""}${memoryText}`;}
async function fetchWithTimeout(url, options = {}, timeoutMs = DEFAULT_TIMEOUT_MS){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),Math.max(1000,timeoutMs));try{return await fetch(url,{...options,signal:controller.signal});}finally{clearTimeout(timer);}}
async function callGroq(messages,studentId,language,councilRole,memories){const key=process.env.GROQ_API_KEY;if(!key)throw new Error("AI provider is not configured");const model=process.env.GROQ_MODEL||process.env.OPENAI_MODEL||"llama-3.3-70b-versatile";const r=await fetchWithTimeout("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify({model,messages:[{role:"system",content:systemPrompt(studentId,language,councilRole,memories)},...normalizeMessages(messages)],temperature:.7,max_tokens:1000})});if(!r.ok)throw new Error(`Groq request failed (${r.status})`);const d=await r.json().catch(()=>null),t=d?.choices?.[0]?.message?.content?.trim()||"";if(!t)throw new Error("Groq returned an empty response");return t;}
async function callGemini(messages,studentId,language,councilRole,memories){const key=process.env.GEMINI_API_KEY;if(!key)throw new Error("AI provider is not configured");const model=process.env.GEMINI_MODEL||"gemini-3.6-flash";const contents=normalizeMessages(messages).map(m=>({role:m.role==="assistant"?"model":"user",parts:[{text:m.content}]}));const r=await fetchWithTimeout(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":key},body:JSON.stringify({contents,generationConfig:{temperature:.7,maxOutputTokens:1000},systemInstruction:{parts:[{text:systemPrompt(studentId,language,councilRole,memories)}]}})});if(!r.ok)throw new Error(`Gemini request failed (${r.status})`);const d=await r.json().catch(()=>null),t=d?.candidates?.[0]?.content?.parts?.map(p=>p?.text||"").join("").trim()||"";if(!t)throw new Error("Gemini returned an empty response");return t;}
async function callOpenAI(messages,studentId,language,councilRole,memories){const key=process.env.OPENAI_API_KEY;if(!key)throw new Error("AI provider is not configured");const model=process.env.OPENAI_MODEL||"gpt-4o-mini";const r=await fetchWithTimeout("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify({model,messages:[{role:"system",content:systemPrompt(studentId,language,councilRole,memories)},...normalizeMessages(messages)],temperature:.7,max_tokens:1000})});if(!r.ok)throw new Error(`OpenAI request failed (${r.status})`);const d=await r.json().catch(()=>null),t=d?.choices?.[0]?.message?.content?.trim()||"";if(!t)throw new Error("OpenAI returned an empty response");return t;}
const CALLERS={groq:callGroq,openai:callOpenAI,gemini:callGemini};

export async function generateAIReply({message="",studentId="",history=[],language="",councilRole=""}={}){const cleanMessage=String(message).trim();if(!cleanMessage)throw new Error("Message is required.");const messages=[...normalizeMessages(history),{role:"user",content:cleanMessage}],memories=await recallMemories(studentId,cleanMessage),route=councilRoute(cleanMessage),assignedRole=councilRole||route.routedTo,providers=configuredProviders();if(route.status!=="PASS")throw new Error(`Request blocked: ${route.reason}`);if(!providers.length)throw new Error("AI provider is not configured");let lastError;const controlled=await runControlledTask({message:cleanMessage,owner:assignedRole,timeoutMs:DEFAULT_TIMEOUT_MS,execute:async()=>{for(const provider of providers){try{const text=await CALLERS[provider](messages,studentId,language,assignedRole,memories);const persisted=await saveMemory(studentId,{user:cleanMessage,assistant:text,councilRole:assignedRole});console.log(`MA-AI.PS department ${assignedRole} provider success: ${provider}`);return {text,sources:[],retrievalMode:memoryEnabled()?(memories.length?"long_term_memory":"memory_enabled_no_match"):"provider_only",memoriesUsed:memories.length,memoryPersisted:persisted,councilRole:assignedRole,provider};}catch(error){lastError=error;console.error(`K.AI.S provider failed: ${provider}`,error?.message||"unknown error");}}throw new Error(`All configured AI providers failed: ${lastError?.message||"unknown error"}`);}});return controlled.result;}
