import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import sharp from "sharp";
import ffmpegPath from "ffmpeg-static";

const execFileAsync = promisify(execFile);
const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const outputDir = path.join(root, "public", "generated", "studio");
function clean(value, fallback = "") { return String(value ?? fallback).replace(/[<>]/g, "").trim().slice(0, 220); }
function esc(value) { return String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;"); }
function wrap(text, max = 28) { const words=String(text).split(/\s+/); const lines=[]; let line=""; for(const word of words){const next=line?line+" "+word:word;if(next.length>max&&line){lines.push(line);line=word;}else line=next;} if(line)lines.push(line); return lines.slice(0,4); }
export const STUDIO_SUBORDINATES = Object.freeze(["STUDIO_COPYWRITER","STUDIO_ART_DIRECTOR","STUDIO_VIDEO_PRODUCER","STUDIO_MOTION_EDITOR"]);
export function buildCreativeBrief(input={}) { const title=clean(input.title,"MA.AI.PS"); const headline=clean(input.headline,"One World. One Language. Intelligent Solutions."); const offer=clean(input.offer,"Digital intelligence for people and businesses."); const cta=clean(input.cta,"Explore K.A.I.S"); const url=clean(input.url,"https://ma-aips-ai.hatchable.site/"); return {title,headline,offer,cta,url,format:clean(input.format,"9:16"),duration:Math.min(15,Math.max(5,Number(input.duration)||8)),studio:"CREATIVE_STUDIO",subordinates:STUDIO_SUBORDINATES}; }
function posterSvg(brief) {
 const lines=wrap(brief.headline,25);
 const headline=lines.map((line,i)=>'<text x="92" y="'+(500+i*88)+'" class="headline">'+esc(line)+'</text>').join("");
 const offerY=500+lines.length*88+70;
 return '<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#07111f"/><stop offset=".48" stop-color="#102b4d"/><stop offset="1" stop-color="#0b5f66"/></linearGradient><radialGradient id="orb"><stop offset="0" stop-color="#8cf5e5" stop-opacity=".85"/><stop offset="1" stop-color="#8cf5e5" stop-opacity="0"/></radialGradient><filter id="blur"><feGaussianBlur stdDeviation="28"/></filter><style>.brand{font:700 34px Arial;letter-spacing:4px;fill:#d9fffa}.eyebrow{font:700 22px Arial;letter-spacing:5px;fill:#8cf5e5}.headline{font:800 78px Arial;fill:#fff}.offer{font:400 34px Arial;fill:#d7e7f5}.cta{font:800 28px Arial;fill:#07111f}.url{font:600 22px Arial;fill:#c7fff8}</style></defs><rect width="1080" height="1920" fill="url(#bg)"/><circle cx="220" cy="330" r="330" fill="url(#orb)" filter="url(#blur)"/><circle cx="850" cy="1420" r="420" fill="url(#orb)" opacity=".55" filter="url(#blur)"/><path d="M0 1450 C280 1300 420 1660 720 1500 S1000 1370 1080 1430 V1920 H0Z" fill="#06101c" opacity=".58"/><text x="92" y="120" class="brand">'+esc(brief.title)+'</text><text x="92" y="260" class="eyebrow">CREATIVE STUDIO • PREMIUM AD</text>'+headline+'<text x="92" y="'+offerY+'" class="offer">'+esc(brief.offer)+'</text><rect x="92" y="1500" rx="28" width="470" height="92" fill="#8cf5e5"/><text x="145" y="1558" class="cta">'+esc(brief.cta)+'</text><text x="92" y="1690" class="url">'+esc(brief.url)+'</text><text x="92" y="1815" class="eyebrow">ONE WORLD • ONE LANGUAGE</text></svg>';
}
async function renderPoster(brief,base){ await fs.mkdir(outputDir,{recursive:true}); const pngPath=path.join(outputDir,base+".png"); await sharp(Buffer.from(posterSvg(brief))).png().toFile(pngPath); return pngPath; }
async function renderVideo(brief,base){ if(!ffmpegPath) throw new Error("FFmpeg renderer unavailable"); await fs.mkdir(outputDir,{recursive:true}); const pngPath=path.join(outputDir,base+"-frame.png"); const mp4Path=path.join(outputDir,base+".mp4"); await sharp(Buffer.from(posterSvg(brief))).png().toFile(pngPath); await execFileAsync(ffmpegPath,["-y","-loop","1","-i",pngPath,"-t",String(brief.duration),"-vf","scale=1080:1920,zoompan=z='min(zoom+0.0008,1.06)':x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':d=1:s=1080x1920:fps=30,format=yuv420p","-an","-movflags","+faststart","-c:v","libx264","-preset","veryfast","-crf","20",mp4Path],{maxBuffer:8*1024*1024}); return mp4Path; }
export async function createStudioAd(input={}){ const brief=buildCreativeBrief(input); const base="ad-"+Date.now(); await renderPoster(brief,base); await renderVideo(brief,base); const publicBase="/generated/studio/"+base; return {ok:true,department:"CREATIVE_STUDIO",subordinates:STUDIO_SUBORDINATES,posterUrl:publicBase+".png",videoUrl:publicBase+".mp4",brief,capabilities:["premium copy","poster generation","MP4 video rendering","motion","9:16 social ads"]}; }